MAX_TWEET_CHARS = 140
SEARCH_QUERY = '@TwitDoghouse'
SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = 60
MINUTES_IN_DAY = MINUTES_IN_HOUR * 24
TEXT_AREA_ROWS = 4
DOGHOUSES_PER_PAGE = 5
BITLY_LINK = 'http://bit.ly/LcFVjZ'